export const GET_USERS_DATA = "GET_USERS_DATA";
export const GET_QUESTIONS_DATA = "GET_QUESTIONS_DATA";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const ADD_QUESTION = "ADD_QUESTION";
